interfacing ultrasonic and led
iparkmse/ipark-embd pull request #6
Opened 2019-02-27 23:22 UTC by Jack-Neng

## 🚀 What does this PR implement/fix?
* This PR is to implement feature of interfacing the ultrasonic sensor and led.

## 📖 Where should the reviewers start?
* Reviewer should start inside the /src/main.cpp (that is the main script).

## 🎥 Screencast/Demo

## 💡 Additional context you want to provide?

2019-02-28 05:16 UTC, tomliangg commented on src/main.cpp
> +int ultra_sensing(int trigPin, int echoPin)
might be a good idea to keep your function naming consistent. For example, all Arduino built-in functions use camel case (i.e. pinMode(x), delayMicroseconds(x)). `ultra_sensing` -> `ultraSensing`

some good Arduino style guide we can follow: https://sites.google.com/a/cabrillo.edu/cs-11m/howtos/cppdoc

2019-02-28 05:16 UTC, tomliangg commented on src/main.cpp
> +{
let's keep the bracket style consistent. Since in setup and loop we put the bracket in the same line, let do the same for all the functions. 
Instead of 

> int ultraSensing(int trigPin, int echoPin)  
> {  
>     // codes  
> }

Do

> int ultraSensing(int trigPin, int echoPin) {  
>     // codes  
> }

2019-02-28 05:16 UTC, tomliangg commented on src/main.cpp
> +void shift_out_data(int data_pattern)
function naming use camelCase. Fix the bracket too

2019-02-28 05:16 UTC, tomliangg commented on src/main.cpp
> +uint8_t turn_led_red(int distance, int n)
function naming. Bracket style

2019-02-28 05:16 UTC, tomliangg commented on src/main.cpp
> +int min_distance = 0; // minimum sensing distance
keep the variable naming style consistent too. If you did camelCase like `echoPin1`, do the same to `minDistance`.
Reference: https://sites.google.com/a/cabrillo.edu/cs-11m/howtos/cppdoc#TOC-Variable-Names

2019-02-28 21:43 UTC, firwjya commented on src/main.cpp
> +void shift_out_data(int data_pattern)
Can you also give a brief description of the function usage?

2019-02-28 21:43 UTC, firwjya commented on src/main.cpp
> +uint8_t turn_led_red(int distance, int n)
This one too :) Thanks

2019-03-14 00:47 UTC, tomliangg requested changes

2019-03-14 00:47 UTC, tomliangg commented on src/main.cpp
> +  for (i = 0; i < 4; i = i + 1) {
just wondering why don't use `i++` over `i = i+1`? cpplint style problem?

2019-03-14 00:47 UTC, tomliangg commented on src/main.cpp
> +  delay(100);  // Fetching data from firebase every 3 seconds
need to update this comment since we changed the delay time

2019-03-14 00:47 UTC, tomliangg commented on src/main.cpp
> +  int i;
Think we can clean up by putting `int i` inside the for loop:
for (char i = 0; i < 4; i++) {

}

2019-03-14 00:47 UTC, tomliangg commented on src/main.cpp
> +  int i;
use `char` over `int` too so we can save some memory space if the variable is not going to grow big

2019-03-14 00:47 UTC, tomliangg commented on src/main.cpp
> +void sensor_led_interfaces() {
spotted a snake case here :stuck_out_tongue:

2019-03-14 00:47 UTC, Jack-Neng commented on src/main.cpp
> +void sensor_led_interfaces() {
opps

2019-03-14 00:56 UTC, Jack-Neng commented on src/main.cpp
> +  int i;
isnt char for character only?
i will have warning if i change to char:
> src/main.cpp: In function 'void sensorLedInterfaces()':
> src/main.cpp:147:36: warning: array subscript has type 'char' [-Wchar-subscripts]
> int led = turnLedRed(distance[i], i);

2019-03-14 01:07 UTC, tomliangg commented on src/main.cpp
> +  int i;
my bad. I mixed up with C... In C we can do initialize a small number with `char` but not in C++.
Hmm in this case, we can do `uint8_t i = 0`

2019-03-14 01:07 UTC, Jack-Neng commented on src/main.cpp
> +  int i;
kk

2019-03-14 01:57 UTC, tomliangg requested changes
Just a few places need too add spaces to enhance code readability. ref: https://introcs.cs.princeton.edu/java/11style/

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +    // Ultrasonic sensors
let's keep the spacing/indentation consistent. Like #40, give the same number of spaces to // as the line below

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +    // Ultrasonic sensors
what it looks to me it's one or two extra spaces here

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +  String stallStatus = Firebase.getString("stalls/"+ stallNumber + "/status/");
we can space this out to improve the readability:
`"stalls/"+ stallNumber + "/status/"`   
->  
`"stalls/" + stallNumber + "/status/"`

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +  Serial.println("The status of "+ stallNumber + "is "+ stallStatus);
same as above. space out

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +  // Writing stall status
add more spaces here before `//` comment

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +  // Delay
we can remove this comment since the purpose is obvious

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +    Firebase.setString("stalls/"+stallNumber+"/status/", status);
spacing: `"stalls/" + stallNumber + "/status/", status`

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +    Serial.print("Updating "+stallNumber+" to "+status);
spacing, same as above

2019-03-14 01:57 UTC, tomliangg commented on src/main.cpp
> +  shiftOutData(ledPattern+trigPin);
space

2019-03-14 04:57 UTC, tomliangg approved these changes
Great work

2019-03-14 06:10 UTC, tomliangg commented
general comment, try to write a more informative commit message. Refer to https://chris.beams.io/posts/git-commit/

2019-03-15 04:44 UTC, firwjya approved these changes
Awesome!!

2019-03-18 21:26 UTC, merged